package com.gtocore.common.machine.mana.multiblock;

import com.gtocore.api.machine.part.GTOPartAbility;
import com.gtocore.common.data.GTOBlocks;
import com.gtocore.data.IdleReason;

import com.gtolib.api.annotation.DataGeneratorScanned;
import com.gtolib.api.annotation.language.RegisterLanguage;
import com.gtolib.api.data.GTODimensions;
import com.gtolib.utils.RegistriesUtils;

import com.gregtechceu.gtceu.api.blockentity.MetaMachineBlockEntity;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblockpro.ParamKey;
import com.gregtechceu.gtceu.api.machine.multiblockpro.Piece;
import com.gregtechceu.gtceu.api.machine.multiblockpro.PortKey;
import com.gregtechceu.gtceu.api.machine.multiblockpro.Slot;
import com.gregtechceu.gtceu.api.machine.multiblockpro.Structure;
import com.gregtechceu.gtceu.api.machine.multiblockpro.Symbols;
import com.gregtechceu.gtceu.api.recipe.GTRecipeDefinition;
import com.gregtechceu.gtceu.api.recipe.handler.RecipeHandlerUnit;

import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Blocks;

import org.jetbrains.annotations.NotNull;

import static com.gregtechceu.gtceu.api.machine.multiblock.PartAbility.*;
import static com.gregtechceu.gtceu.api.pattern.Predicates.*;
import static com.gregtechceu.gtceu.api.pattern.util.RelativeDirection.*;

@DataGeneratorScanned
public final class ManaCondenserMachine extends ManaMultiblockMachine {

    public static final PortKey FORM_OUT = PortKey.of("form_out");
    public static final PortKey FORM_IN = PortKey.of("form_in");
    @RegisterLanguage(cn = "阵列形态", en = "Array Form")
    private static final String FORM_NAME = "gtocore.multiblock.mana_condenser.form";
    @RegisterLanguage(cn = "第一项为常规形态，用于亚尔夫海姆以外的维度；第二项为亚尔夫海姆形态，仅用于亚尔夫海姆", en = "The first option is the standard form for dimensions other than Alfheim; the second is the Alfheim form, used only in Alfheim")
    private static final String FORM_DESC = "gtocore.multiblock.mana_condenser.form.desc";
    public static final ParamKey FORM = ParamKey.of(FORM_NAME, FORM_DESC);

    private int requiredForm = 1;

    public ManaCondenserMachine(MetaMachineBlockEntity holder) {
        super(holder);
    }

    @Override
    public void onLoad() {
        super.onLoad();
        Level level = getLevel();
        if (level == null) return;
        requiredForm = level.dimension() == GTODimensions.ALFHEIM ? 2 : 1;
    }

    @Override
    public boolean checkConditions(RecipeHandlerUnit unit, @NotNull GTRecipeDefinition recipe) {
        if (structureParam(FORM) != requiredForm) {
            setIdleReason(IdleReason.MANA_CONDENSER_FORM);
            return false;
        }
        return super.checkConditions(unit, recipe);
    }

    public static Structure structure(MultiblockMachineDefinition definition) {
        return Structure.root(Piece.start(BACK, UP, LEFT)
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "       A       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "       A       ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "         A     ", "         D     ", "     A   D     ", "     D   D     ", "     D   D     ", "     D   D     ", "     DDDDD     ", "     A   A     ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "     DAAAD     ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "          D    ", "          D    ", "          D    ", "    A     D    ", "    D     D    ", "    D     D    ", "    DDAAADD    ", "    A  C  A    ", "      O        ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "     DAAAD     ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "         D     ", "         D     ", "         D     ", "         D     ", "         D     ", "     A   D     ", "     D   D     ", "     DDDDD     ", "     A   A     ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "      ADA      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "      ADA      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("       B       ", "       A       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "    AACDCAA    ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C A      ", "      C        ", "      A        ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "         B     ", "         A     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "   ACCDDDCCA   ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          A    ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "           B   ", "           A   ", "           C   ", "           C   ", "           C   ", "           C   ", "           C   ", "           C   ", "           C   ", "           C   ", "      E    C   ", "      A E  C   ", "      D A  C   ", "      D D  C   ", "      D D  C   ", "  ACDDDDDDDCA  ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      DCD      ", "      A A      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "    E          ", "    A          ", "    D          ", "    D          ", "    D          ", "    D          ", " ACDDDDDDDDDCA ", "    D  F  D C  ", "    D     D C  ", "    D     D C  ", "    D     D C  ", "    D     D C  ", "    D AAA D C  ", "    DCCCCCD C  ", "    A     A C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            A  ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "            B  ", "            A  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", " ACDDDDGDDDDCA ", "     F   F     ", "               ", "               ", "               ", "               ", "     A   A     ", "    CCHHHCC    ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "   E           ", "   A   A       ", "   D   A       ", "   D   A       ", "   D           ", "   D           ", "   D  G G      ", "ACDDDDGHGDDDDCA", "   D       D C ", "   D       D C ", "   D       D C ", "   D       D C ", "   D       D C ", "   DA     AD C ", "   DCHCCCHCD C ", "   D  IJI  D C ", "   D       D C ", "   A       D C ", "           D C ", "           D A ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           A   ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "             B ", "             A ", "             C ", "             C ", "       A     C ", "      A A    C ", "      AKA    C ", "      A A    C ", "       A     C ", "             C ", "             C ", "ACDDDGHHHGDDDCA", "    F  L  F    ", "               ", "               ", "               ", "               ", "    A     A    ", "   CCHCCCHCC   ", "      JJJ      ", "       M       ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "   E           ", "   A           ", "   D   A       ", "   D   A       ", "   D   A       ", "   D           ", "   D           ", "   D  G G      ", "ACDDD GHGDDDDCA", "   D       D C ", "   D       D C ", "   D       D C ", "   D       D C ", "   D       D C ", "   DA     AD C ", "   DCHCCCHCD C ", "   D  IJI  D C ", "   D       D C ", "   D       D A ", "   D       D   ", "   A       D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           A   ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "            B  ", "            A  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", " ACD   GDDDDCA ", "     F   F     ", "               ", "               ", "               ", "               ", "     A   A     ", "    CCHHHCC    ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "    E          ", "    A          ", "    D          ", "    D          ", "    D          ", "    D          ", "    D          ", "    D          ", "    D          ", " AC   DDDDDDCA ", "    D  F  D C  ", "    D     D C  ", "    D     D C  ", "    D     D C  ", "    D     D C  ", "    D AAA D C  ", "    DCCCCCD C  ", "    D     D A  ", "    D     D    ", "    D     D    ", "    D     D    ", "    D     D    ", "    D     D    ", "    A     D    ", "          D    ", "          D    ", "          D    ", "          D    ", "          D    ", "          A    ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "        E      ", "      E A      ", "      A D      ", "      D D      ", "      D D  B   ", "      D D  A   ", "      D D  C   ", "      D D  C   ", "      D D  C   ", "      D D  C   ", "      D D  C   ", "     DDDDDDCA  ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      DCD      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      A D      ", "        D      ", "        A      ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "         B     ", "         A     ", "         C     ", "         C     ", "         C     ", "    CCDDDCCA   ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          A    ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "       B       ", "       A       ", "       C       ", "    AACCCA     ", "      C C      ", "      A C      ", "        C      ", "        A      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "      AAA      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                .port('O', FORM_OUT, BACK)
                .build())
                .symbols(Symbols.create()
                        .where('@', any())
                        .where('A', blocks(RegistriesUtils.getBlock("botania:elf_glass")))
                        .where('B', blocks(RegistriesUtils.getBlock("botania:natura_pylon")))
                        .where('C', blocks(GTOBlocks.MANASTEEL_CASING.get()))
                        .where('D', blocks(GTOBlocks.ELEMENTIUM_CASING.get()))
                        .where('E', blocks(RegistriesUtils.getBlock("botania:mana_pylon")))
                        .where('F', blocks(RegistriesUtils.getBlock("botania:apothecary_livingrock")))
                        .where('G', blocks(RegistriesUtils.getBlock("botania:glimmering_dreamwood")))
                        .where('H', blocks(RegistriesUtils.getBlock("botania:glimmering_livingwood")))
                        .where('I', blocks(Blocks.LAPIS_BLOCK))
                        .where('J', blocks(RegistriesUtils.getBlock("botania:livingrock")))
                        .where('K', blocks(RegistriesUtils.getBlock("botania:corporea_index")))
                        .where('L', blocks(RegistriesUtils.getBlock("botania:runic_altar")))
                        .where('M', blocks(RegistriesUtils.getBlock("botania:terra_plate")))
                        .wherePart('N', blocks(GTOBlocks.MANASTEEL_CASING.get())
                                .or(abilities(GTOPartAbility.INPUT_MANA).setMaxGlobalLimited(16, 1))
                                .or(abilities(PARALLEL_HATCH).setMaxGlobalLimited(1))
                                .or(abilities(IMPORT_FLUIDS).setMaxGlobalLimited(4, 1))
                                .or(abilities(EXPORT_ITEMS).setMaxGlobalLimited(4, 1))
                                .or(abilities(IMPORT_ITEMS).setMaxGlobalLimited(4, 1)))
                        .where('O', controller(definition))
                        .where('b', blocks(RegistriesUtils.getBlock("mythicbotany:alfsteel_pylon")))
                        .where('c', blocks(RegistriesUtils.getBlock("botania:bifrost_perm")))
                        .where('d', blocks(GTOBlocks.GAIASTEEL_CASING.get()))
                        .where('e', blocks(RegistriesUtils.getBlock("botania:shimmerrock")))
                        .where('f', blocks(Blocks.GOLD_BLOCK))
                        .where('g', blocks(RegistriesUtils.getBlock("mythicbotany:alfsteel_block")))
                        .where('h', blocks(RegistriesUtils.getBlock("mythicbotany:mana_infuser")))
                        .wherePart('u', blocks(GTOBlocks.MANASTEEL_CASING.get())
                                .or(abilities(GTOPartAbility.INPUT_MANA).setMaxGlobalLimited(32, 1))
                                .or(abilities(PARALLEL_HATCH).setMaxGlobalLimited(1))
                                .or(abilities(IMPORT_FLUIDS).setMaxGlobalLimited(4, 1))
                                .or(abilities(EXPORT_ITEMS).setMaxGlobalLimited(4, 1))
                                .or(abilities(IMPORT_ITEMS).setMaxGlobalLimited(4, 1))))
                .atPort(FORM_OUT, Slot.choice(Slot.one(standardForm(), FORM_IN), Slot.one(alfheimForm(), FORM_IN)).count(FORM))
                .build();
    }

    private static Piece standardForm() {
        return Piece.start(BACK, UP, LEFT)
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "    NNN  ", "    NNN  ", "    NNN  ")
                .aisle("         ", "         ", "         ", "        A", "        D", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "    N N  ", "     @N  ", "    NNN  ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "    NNN  ", "    NNN  ", "    NNN  ")
                .aisle("         ", "         ", "       A ", "       D ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ")
                .aisle("     A   ", "     D   ", "     D   ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "   D     ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "  DDD    ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", " DDD     ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "ACD      ", "         ", "         ", "         ")
                .aisle("         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", "         ", " A       ", "         ", "         ", "         ")
                .port('@', FORM_IN, FRONT)
                .build();
    }

    private static Piece alfheimForm() {
        return Piece.start(BACK, UP, LEFT)
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "           uuu  ", "           uuu  ", "           uuu  ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "               A", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "           u u  ", "            @u  ", "           uuu  ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "           uuu  ", "           uuu  ", "           uuu  ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "              A ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "            A   ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "          d     ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "         ddd    ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "        ddd     ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "    AAAddd      ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "    b           ", "    c           ", "    d           ", "  AAdAddd       ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    c           ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "  b             ", "  c             ", "  d             ", "  d             ", "  d             ", " AddddddA       ", "  d             ", "  d             ", "  d             ", "  d             ", "  d             ", "  d             ", "  d             ", "  d             ", "  d             ", "  d             ", "  d             ", "  d             ", "  c             ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "    c           ", "                ", "                ", "                ", " AdddddAA       ", "   efe          ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("       b        ", "       c        ", "       d        ", "       d        ", "       d        ", "       d        ", "       d        ", "       d        ", " b     d        ", " c     d        ", " d  c  d        ", " d cgc d        ", " d  c  d        ", " d     d        ", " d     d        ", "AdddcdddA       ", " d fef d        ", " d  h  d        ", " d     c        ", " d              ", " d              ", " d              ", " d              ", " d              ", " d              ", " d              ", " c              ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "    c           ", "                ", "                ", "                ", " AdddddA        ", "   efe          ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "      b         ", "      c         ", "      d         ", "      d         ", "  b   d         ", "  c   d         ", "  d   d         ", "  d   d         ", "  d   d         ", "  d   d         ", "  d   d         ", "  d   d         ", "  d   d         ", " AdddddA        ", "  d   d         ", "  d   d         ", "  d   d         ", "  d   d         ", "  d   c         ", "  d             ", "  d             ", "  d             ", "  c             ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "    b           ", "    c           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "  AAdAA         ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    d           ", "    c           ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .aisle("                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "    A           ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ", "                ")
                .port('@', FORM_IN, FRONT)
                .build();
    }
}
